Repository BSC-ES/autosubmit, pull requests merged in 2025-07, with the labels that each got.

#2453 [Documentation] CONTRIBUTING.md run Slurm
  CONTRIBUTING.md
Labels: documentation

#2449 Getting rid of unused code, and doing some cleaning
  autosubmit/autosubmit.py
  autosubmit/job/job_utils.py
Labels: Refactor

#2452 [Documentation] Adding new users to documentation
  CHANGELOG.md
  autosubmit/job/job_utils.py
  docs/source/_static/logos/esiwace.png
  docs/source/_static/logos/ganana.png
  docs/source/_static/logos/hpcw.png
  docs/source/_static/logos/terradt.png
  docs/source/index.rst
Labels: documentation

#2457 [Documentation] NUMTHREAD wrong use
  docs/source/userguide/variables.rst
Labels: documentation

#2459 [Refactoring] Redundant functions
  autosubmit/autosubmit.py
  autosubmit/history/utils.py
  autosubmit/monitor/monitor.py
Labels: Refactor

#2460 [Documentation] - Fixing documentation
  docs/source/userguide/defining_workflows/fig/splits_1_to_1.png
  docs/source/userguide/defining_workflows/fig/splits_job.png
  docs/source/userguide/defining_workflows/index.rst
Labels: documentation

#2451 Fix git check for operational experiments
  CHANGELOG.md
  CONTRIBUTING.md
  autosubmit/autosubmit.py
  autosubmit/git/autosubmit_git.py
  docs/source/userguide/run/index.rst
  test/conftest.py
  test/integration/git/__init__.py
  test/integration/git/test_autosubmit_git.py
  test/integration/scripts/test_clean.py
  test/integration/test_utils/git.py
  test/unit/git/__init__.py
  test/unit/git/test_autosubmit_git.py
Labels: bug
