Repository BSC-ES/autosubmit, pull requests merged in 2025-05, with the labels that each got.

#2310 first commit documenting the wrappers
  autosubmit/job/job.py
  autosubmit/platforms/paramiko_platform.py
  test/unit/test_platform.py
Labels: enhancement

#2327 Wrapper status is not updated correctly
  CHANGELOG.md
  autosubmit/job/job.py
  autosubmit/job/job_common.py
  autosubmit/platforms/platform.py
  test/unit/test_platform.py
Labels: bug

#2256 Removing unused function from parent class
  autosubmit/platforms/paramiko_platform.py
  autosubmit/platforms/paramiko_submitter.py
Labels: enhancement, Refactor

#2190 job_list: Adjusting to remove unused variable
  autosubmit/job/job_list.py
  test/unit/test_job_list.py
Labels: enhancement, Refactor

#2169 diagram seq and populate_statistics test
  test/conftest.py
  test/unit/test_diagram.py
  test/unit/test_statistics.py
Labels: enhancement

#2170 Test create stats report
  test/unit/test_diagram.py
  test/unit/test_job_list.py
Labels: enhancement

#2162 test handle_start_after and refactoring code
  autosubmit/autosubmit.py
  autosubmit/helpers/autosubmit_helper.py
  test/integration/test_log_recovery.py
  test/unit/test_autosubmit_helper.py
Labels: enhancement, Refactor

#2205 Job: second commit vulture fix
  autosubmit/job/job.py
Labels: enhancement, Refactor

#2036 Feature: Job metrics
  autosubmit/autosubmit.py
  autosubmit/history/database_managers/experiment_history_db_manager.py
  autosubmit/job/job.py
  autosubmit/job/metrics_processor.py
  autosubmit/platforms/locplatform.py
  autosubmit/platforms/paramiko_platform.py
  autosubmit/platforms/pjmplatform.py
  autosubmit/platforms/platform.py
  autosubmit/platforms/slurmplatform.py
  docs/source/troubleshooting/error-codes.rst
  docs/source/userguide/index.rst
  docs/source/userguide/user_metrics/index.rst
  test/unit/test_local_platform.py
  test/unit/test_platform.py
  test/unit/test_user_metrics.py
Labels: new feature
