Repository BSC-ES/autosubmit, pull requests merged in 2025-04, with the labels that each got.

#2262 fixing f-string the error
  autosubmit/job/job_list.py
Labels: enhancement, Refactor

#2263 fixing f-string the error
  autosubmit/platforms/paramiko_platform.py
Labels: enhancement, Refactor

#2268 fixing f-string error C0209 autosubmit.py
  autosubmit/autosubmit.py
Labels: enhancement, Refactor

#2257 standardizing the Docstring
  autosubmit/autosubmit.py
  autosubmit/history/database_managers/experiment_history_db_manager.py
  autosubmit/history/experiment_history.py
  autosubmit/job/job.py
  autosubmit/job/job_list.py
  autosubmit/job/job_packager.py
  autosubmit/job/job_packages.py
  autosubmit/platforms/ecplatform.py
  autosubmit/platforms/locplatform.py
  autosubmit/platforms/paramiko_platform.py
  autosubmit/platforms/platform.py
  autosubmit/platforms/slurmplatform.py
  autosubmit/platforms/wrappers/wrapper_builder.py
Labels: documentation, enhancement, Refactor

#2296 Update details on expid/delete
  autosubmit/autosubmit.py
  autosubmit/database/db_common.py
  autosubmit/experiment/detail_updater.py
  test/unit/test_detail_updater.py
Labels: enhancement

#2201 Improving error handling message
  autosubmit/autosubmit.py
  autosubmit/experiment/experiment_common.py
Labels: enhancement, Refactor

#2188 status_db_manager: Adjusting to remove unused varible
  autosubmit/history/database_managers/experiment_status_db_manager.py
Labels: enhancement, Refactor
